"""Application-wide constants."""

from web_backend.constants.auth import (
    ACCESS_TOKEN_EXPIRE_MINUTES,
    BCRYPT_ROUNDS,
    REFRESH_COOKIE_NAME,
    REFRESH_TOKEN_EXPIRE_DAYS,
    TOKEN_ALGORITHM,
    TOKEN_TYPE_ACCESS,
    TOKEN_TYPE_REFRESH,
)

__all__ = [
    "ACCESS_TOKEN_EXPIRE_MINUTES",
    "BCRYPT_ROUNDS",
    "REFRESH_COOKIE_NAME",
    "REFRESH_TOKEN_EXPIRE_DAYS",
    "TOKEN_ALGORITHM",
    "TOKEN_TYPE_ACCESS",
    "TOKEN_TYPE_REFRESH",
]
